language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: broker-web-prod
  api_key:
    secure: XMNk7dJxxPC8Tftsv8RHsCi2P7DO8F1k9qA4rXlqxeStnloJnllgCw37DckS6SLQ7Ws5ahTz1Lv6HzY48aFwgn38alkoc8oDPqnPO60a6DoQiNO8xpgYLsfNdUqH440k2ptMpsuKfyQ+2tKzsj0cdz1uAt8xBR//dbcLpo/wHnS1jdSWdd55h4kuwB2Ne7A5meysk5qJkqluJXlP/LMM6gz+gIIKIIpUzCDpZtAsK7GduldCdoC/dUV7ediFsDwoMMjVd30Oe2ZaEfEfEH2YWOvv8RYYatSn4t0m9BuqQY4qDpFacAkbH9eSGMIgtwLVUPdpaqhXAH5UMCF5H/0Gq/VfvvhZCAXXuwGrjmbEZKjC5/mhju8tPkba5dQP6jxsXwPEG7mdOWWesNjK09FMTmg8OqE9VBTF3DCYrz6ec+yeLB5J89RrjTXkVormYtkUjlKSqSs/SGXeVebgo0VAsqeCGFejAIe3fEkJJFDeJxWATUk4GAKpz+dR9cvZRKCy6YvPsFbfRg7TYaYDvW/tfk6igCX/KeS1TAVw810FNpbvl4CURgytpTPKuidWXCOeb8eeM6CaS6OKbtPT4Z7c9NawJvyJpRfFcPO0ri2DL0fVW1mPPeOUudnBEI4PdNherAsIhW51vLIhjg9z8QJ9VR4UKoeHfKMEFk3FUFqVceU=
