language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: broker-web-dev
  api_key:
    secure: W//wZ4UnpujruQhplkx5ozopBy44YzkX4brHptGFHiWlE59oIZgo3iLDhZsLWbqEg6eqPZOPtf5L6rzayV/nT7jqqpPI6m1mg+JKQBEba7T9cj+FsnVZpi/74MaA97mpVQWb29zllrCMO6uSUh+rHPMPYBCJ4nhX+jrFmXYcQSoOki/tixfbDZvzCBY063hSMwyaR5SfQ4JY2As6RHiS0IWde37uAjhABrJYHGoWAYzhkGDIQZIB59WrtOFojJNFrU+75sQGoULHdwXOZeJccXp7tSTaqn9wsHxJ6sxN4Ly6QEdJdy6pKFU83twrpSiuJWndfiKDPKml7F8iiJZGb112gjghjJGvAo3fbdAlSkOTFT63j+2LsUX3nY2zKQceCoXneOG4UJ0xc5LLtDR/BtJaoQ4X4cxPLVZMcFcEaWRvD5xJiPIfSYss+jqgf0cyVCy72vZBb8+c3aaHx8hZc5+yGhEjuqnIErgOZ4EOEWp6V75GDOL7UaaTHc1fy8i1FiS2783vrQjmnKmTnNwTbw1qsYQTiN+XOTunBYhRaAHp/1sZMQka5W76mArG+YcnTS08JuMoJ0oZikYmJ90/lT3E42lx8e/ZYW8asPLxN7fae7oib2cbZu1GfZWcG9VB4otOWQ7pvxHPxi505TYvH161KIn43B4ORDhmzbogZiM=
